### ISSUE TITLE
连接平板失败

### ISSUE THREAD

**Issue by nik-nul** [HexoCustomPass/Myipad-WebSocket#2]
点击启动服务器显示服务器已启动
输入账号后点击链接到平板或客户端校验均无反应，经测试下面的功能也无效
平板与手机已连接到同一wifi下
少年派版本：5.2.3.52408
平板型号：Lenovo TB-X605M
系统版本：TB-X605M_RF01_20220316_NingBoRuiYI

**Comment by HexoCustomPass** [comment]
请问你的账号域名是什么，估计被封了 或者是你操作不对

**Comment by o81018o** [comment]
好家伙，少年派这么大意，安装包都没加固，还能反编译出来

**Comment by nik-nul** [comment]
> 请问你的账号域名是什么，估计被封了 或者是你操作不对

qdez

**Comment by Hexrotor** [comment]
qdez的websocket功能被服务器关了

**Comment by nik-nul** [comment]
> qdez的websocket功能被服务器关了

已证实，感谢

**Comment by nik-nul** [comment]
服务端关闭WebSocket功能，不可使用
